services:
  sandbox:
    image: ghcr.io/oliverilp/online-sandbox:latest@sha256:08118e14c6f16d99d1dea9d6ab7a0c86a10ae0a34297a129608d28cc3a12559c
    container_name: online-sandbox
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nginx.rule=Host(`code.tailkeep.org`)'
      - 'traefik.http.routers.nginx.entrypoints=https'
      - 'traefik.http.routers.nginx.tls=true'
      - 'traefik.http.services.nginx.loadbalancer.server.port=4000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true
